/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lazy_wifi_utils_Crypto */

#ifndef _Included_com_lazy_wifi_utils_Crypto
#define _Included_com_lazy_wifi_utils_Crypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lazy_wifi_utils_Crypto
 * Method:    native_encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lazy_wifi_utils_Crypto_native_1encode
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_lazy_wifi_utils_Crypto
 * Method:    native_decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lazy_wifi_utils_Crypto_native_1decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
